name: Update 3D Contributions

on:
  push:
    branches:
      - main

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: GitHub-Profile-3D-Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
